require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassengerRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # PassengerRecord. As you add validations to PassengerRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "record_date" => "2014-06-09" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PassengerRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all passenger_records as @passenger_records" do
      passenger_record = PassengerRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:passenger_records).should eq([passenger_record])
    end
  end

  describe "GET show" do
    it "assigns the requested passenger_record as @passenger_record" do
      passenger_record = PassengerRecord.create! valid_attributes
      get :show, {:id => passenger_record.to_param}, valid_session
      assigns(:passenger_record).should eq(passenger_record)
    end
  end

  describe "GET new" do
    it "assigns a new passenger_record as @passenger_record" do
      get :new, {}, valid_session
      assigns(:passenger_record).should be_a_new(PassengerRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested passenger_record as @passenger_record" do
      passenger_record = PassengerRecord.create! valid_attributes
      get :edit, {:id => passenger_record.to_param}, valid_session
      assigns(:passenger_record).should eq(passenger_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PassengerRecord" do
        expect {
          post :create, {:passenger_record => valid_attributes}, valid_session
        }.to change(PassengerRecord, :count).by(1)
      end

      it "assigns a newly created passenger_record as @passenger_record" do
        post :create, {:passenger_record => valid_attributes}, valid_session
        assigns(:passenger_record).should be_a(PassengerRecord)
        assigns(:passenger_record).should be_persisted
      end

      it "redirects to the created passenger_record" do
        post :create, {:passenger_record => valid_attributes}, valid_session
        response.should redirect_to(PassengerRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passenger_record as @passenger_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerRecord.any_instance.stub(:save).and_return(false)
        post :create, {:passenger_record => { "record_date" => "invalid value" }}, valid_session
        assigns(:passenger_record).should be_a_new(PassengerRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerRecord.any_instance.stub(:save).and_return(false)
        post :create, {:passenger_record => { "record_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passenger_record" do
        passenger_record = PassengerRecord.create! valid_attributes
        # Assuming there are no other passenger_records in the database, this
        # specifies that the PassengerRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PassengerRecord.any_instance.should_receive(:update_attributes).with({ "record_date" => "2014-06-09" })
        put :update, {:id => passenger_record.to_param, :passenger_record => { "record_date" => "2014-06-09" }}, valid_session
      end

      it "assigns the requested passenger_record as @passenger_record" do
        passenger_record = PassengerRecord.create! valid_attributes
        put :update, {:id => passenger_record.to_param, :passenger_record => valid_attributes}, valid_session
        assigns(:passenger_record).should eq(passenger_record)
      end

      it "redirects to the passenger_record" do
        passenger_record = PassengerRecord.create! valid_attributes
        put :update, {:id => passenger_record.to_param, :passenger_record => valid_attributes}, valid_session
        response.should redirect_to(passenger_record)
      end
    end

    describe "with invalid params" do
      it "assigns the passenger_record as @passenger_record" do
        passenger_record = PassengerRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => passenger_record.to_param, :passenger_record => { "record_date" => "invalid value" }}, valid_session
        assigns(:passenger_record).should eq(passenger_record)
      end

      it "re-renders the 'edit' template" do
        passenger_record = PassengerRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => passenger_record.to_param, :passenger_record => { "record_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passenger_record" do
      passenger_record = PassengerRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => passenger_record.to_param}, valid_session
      }.to change(PassengerRecord, :count).by(-1)
    end

    it "redirects to the passenger_records list" do
      passenger_record = PassengerRecord.create! valid_attributes
      delete :destroy, {:id => passenger_record.to_param}, valid_session
      response.should redirect_to(passenger_records_url)
    end
  end

end
